# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

repo_creds: &repo-creds
  uri: git@github.com:vmware-tanzu/observability-event-resource.git
  private_key: ((oer_deploy_key))

# TODO: Remove this when Concourse 7 is released and v1 is included
resource_types:
- name: registry-image-v1
  type: registry-image
  source:
    repository: concourse/registry-image-resource
    tag: '1'

resources:
- name: test-source
  type: git
  source:
    <<: *repo-creds
    paths:
    - 'Dockerfile'
    - 'go.*'
    - '**/*.go'

- name: release-source
  type: git
  source:
    <<: *repo-creds
    fetch_tags: true
    tag_filter: 'v*'

- name: github-registry
  type: registry-image-v1
  source:
    repository: projects.registry.vmware.com/tanzu/observability-event-resource
    username: ((distro-harbor.username))
    password: ((distro-harbor.password))

jobs:
- name: test-on-push
  plan:
  - get: source
    resource: test-source
    trigger: true
  - task: build-image
    privileged: true
    config: 
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: source
      params:
        CONTEXT: source
        REGISTRY_MIRRORS: ((dockerhub-registry-mirror))
      run:
        path: build

- name: build-release
  plan:
  - get: source
    resource: release-source
    trigger: true
  - load_var: version
    file: source/.git/ref
    format: trim
  - task: build-image
    privileged: true
    config: 
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: source
      outputs:
      - name: image
      params:
        CONTEXT: source
        BUILD_ARG_VERSION: ((.:version))
        REGISTRY_MIRRORS: ((dockerhub-registry-mirror))
      run:
        path: build
  - put: github-registry
    params:
      image: image/image.tar
      version: ((.:version))
      bump_aliases: true
    get_params:
      skip_download: true

